### ISSUE TITLE
Fix disqus size

### ISSUE THREAD

**Issue by Naiml007** [amvstrm/amvstrm#22]
![Screenshot_2023-07-30-12-15-06-460_com noob browser](https://github.com/amvstrm/amvstrm/assets/90306726/a10871a9-7aaf-4591-8fea-11f86ee7d614)

**Comment by NYT92** [comment]
I have added prefers color scheme for both dark and light mode for it which is why Disqus looks small and the background turn white when it is on the light mode.

```css
@media (prefers-color-scheme: dark) {
  iframe[src*="disqus.com"] {
    color-scheme: light;
  }
}

@media (prefers-color-scheme: light) {
  iframe[src*="disqus.com"] {
    color-scheme: light;
  }
}
```
